### ISSUE TITLE
t/mikrotik.t fails with non-English locale

### ISSUE THREAD

**Issue by eserte** [anparker/mikrotik-client#2]
With older perls (I think < 5.22 or < 5.24) the test suite fails if a non-English locale is active (e.g. `LC_ALL=de_DE.UTF-8`):
```
#   Failed test 'connection error'
#   at t/mikrotik.t line 44.
#                   'Verbindung wurde abgelehnt'
#     doesn't match '(?^:Connection refused)'
# Looks like you failed 1 test of 17.
t/mikrotik.t ......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/17 subtests 
```
Typically it's more safe to check using the `$!{E...}` construct --- if `$!` is available in this situation.

**Comment by anparker** [comment]
Fixed, thanks.
