### ISSUE TITLE
the "s" modifier is missing for multi line responses

### ISSUE THREAD

**Issue by stesachse** [anparker/mikrotik-client#3]
https://github.com/anparker/mikrotik-client/blob/8610aa07d323093100feaad85c202b01a746b58a/lib/MikroTik/Client/Response.pm#L25

"." Match any single character except newline (under /s, includes newline)
"/s" Treat the string as single line. That is, change "." to match any character whatsoever, even a newline, which normally it would not match.

https://perldoc.perl.org/perlre#s
https://perldoc.perl.org/perlre#Metacharacters

**Comment by anparker** [comment]
Hi.
I know how re modifiers work, no need to point it out. Fixed in https://github.com/anparker/mikrotik-client/commit/0230153d53cedb4efe7913897da5099c1c529177
Thanks for reporting an issue.
